services:
  postgres-db:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fuse-classroom
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - fuse-classroom
volumes:
  postgres-data:
networks:
  fuse-classroom:
